
# see: https://hub.docker.com/_/jenkins/

# An error occurred during installation: No such plugin: cloudbees-folder
# see: http://stackoverflow.com/questions/37358775/jenkins-2-5-installation-error-an-error-occurred-during-installation-forbidden
# http://local-jenkins:18083/restart

# Find passowrd in console log after initial start.

version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-registry.docker.local}/jenkins:2.32.1-alpine
    restart: always
    container_name: ${JENKINS_HOSTNAME:-local-jenkins}
    hostname: ${JENKINS_HOSTNAME:-local-jenkins}
    ports:
    - "18083:8080/tcp"
    - "50000:50000/tcp"
    volumes:
    - jenkins-master-volume:/var/jenkins_home
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000

volumes:
  jenkins-master-volume: {}

networks:
  default:
    external:
      name: oss-network
